- id: flake8
  name: Flake8
  description: Runs python flake8 via local Pipenv
  entry: pipenv run flake8
  language: system
  types: [python]
  require_serial: true
- id: black
  name: Black
  description: Runs the Black auto-formatter via local Pipenv
  entry: pipenv run black --line-length 120
  language: system
  types: [python]
  require_serial: true
